server:
  servlet:
    context-path: /api/v1

spring:
  cache:
    type: redis
  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: host.docker.internal
    port: 6379
  cloud:
    consul:
      host: host.docker.internal
      discovery:
        ipAddress: host.docker.internal
        preferIpAddress: true
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
