spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.23.130:3306/users
    username: ${username}
    password: ${password}
  redis:
    host: localhost
    port: 6379
  cloud:
    consul:
      host: localhost