spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: ${username}
    password: ${password}
  redis:
    host: localhost
    port: 6379
