spring:
  cache:
    type: redis
  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cloud:
    consul:
      discovery:
        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
  servlet:
    context-path: /api/v1